### ISSUE TITLE
c_formula declaration

### ISSUE THREAD

**Issue by vdelachaux** [mesopelagique/CollectionUtils#1]
With these lines:
``` 4d
C_OBJECT ($ 1)
C_OBJECT ($ 2) // Formula
C_VARIANT ($ {1})
```
You said:
line 1: $1 is an object
line 2: $2 is an object
line 3: All variables since the first are Variant's type. This line hide the 2 precedents & later you use $1 assuming it is an object without testing the value type.

**Comment by mesopelagique** [comment]
thanks

even if its dirty, the compilator seems to give priority to the two first C_OBJECT
(so if un c_formula with no objects in the two first arg, it failed to compile
